DROP TABLE Files_FROM_POLICYHOLDER;
CREATE TABLE Files_FROM_POLICYHOLDER (
	id	INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	id_human	INTEGER,
	uuid_p	varchar(37),
    file_name	CLOB
	);